name: CI

on:
  push:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: CI
        uses: its-me/action.aur.ci@v0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
